version: "3.8"

services:
  data-ingestion:
    build: ./Sensor-Data-Ingestion-Service
    depends_on:
      - rabbitmq
    environment:
      NGROK_URL: https://ee68-41-220-146-91.ngrok-free.app/api/sensor-data/
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
    command: npm run start
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    
  gateway:
    build: ./API_gateway
    depends_on:
      - data-ingestion
    ports:
      - "8080:8080"
    environment:
      DATA_INGESTION_URL: http://data-ingestion:3001/api/sensor-data/
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
    command: node server.js

  dashboard:
      build: ./dashboard
      depends_on:
        - gateway
      ports:
        - "80:3000"
      volumes:
        - ./dashboard:/usr/src/app
        - /usr/src/app/node_modules
      environment:
        GATEWAY_URL: http://gateway:8080/api/sensor-data/ 
        NEXT_PUBLIC_WEBSOCKET_URL: ws://localhost:8080/

  psql:
        image: postgres:alpine3.20
        ports:
          - "5555:5432"
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test

        volumes:
          - ./pg-db:/var/lib/postgresql/data
       

